# Generated by Django 4.0.4 on 2022-09-28 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albumFotos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foto',
            name='foto',
            field=models.ImageField(null=True, upload_to='fotos'),
        ),
    ]
