# Generated by Django 4.0.4 on 2022-09-28 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albumFotos', '0002_foto_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foto',
            name='fecha_foto',
        ),
        migrations.RemoveField(
            model_name='foto',
            name='nombre',
        ),
        migrations.AddField(
            model_name='foto',
            name='titulo',
            field=models.CharField(max_length=100, null=True, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='foto',
            name='foto',
            field=models.ImageField(null=True, upload_to='fotos/', verbose_name='imagen'),
        ),
        migrations.AlterField(
            model_name='foto',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
